import { DemoRecord } from '../../types/demo-record';

export const mockDemoRecords: DemoRecord[] = [
  {
    id: 'demo-1',
    fullName: 'Barış Özcan',
    email: 'baris@futureworks.io',
    companyName: 'FutureWorks Studio',
    companySize: '11-50',
    requestedPlan: 'growth',
    notes: 'Yeni kuracağımız dijital stüdyo için Apple tarzı modern bir SaaS landing page hazırlamak ve entegrasyon yapmak istiyoruz.',
    status: 'pending',
    createdAt: '2026-07-07T05:30:00Z',
    assignedTo: 'Kaan Aksoy',
  },
  {
    id: 'demo-2',
    fullName: 'Dilara Yılmaz',
    email: 'dilara.y@novacore.com',
    companyName: 'NovaCore Technologies',
    companySize: '201-1000',
    requestedPlan: 'enterprise',
    notes: 'Büyük ölçekli veri izleme paneli için Linear tarzı minimalist bir dashboard şablonuna ve rol yönetimi mimarisine ihtiyacımız var.',
    status: 'scheduled',
    createdAt: '2026-07-06T11:45:00Z',
    assignedTo: 'Zeynep Kaya',
  },
  {
    id: 'demo-3',
    fullName: 'Serkan Arslan',
    email: 'serkan@pathfind.net',
    companyName: 'PathFind Logistics',
    companySize: '51-200',
    requestedPlan: 'scale',
    notes: 'Sistem kurulumu tamamlandı, ilk demoyu gerçekleştirdik ve olumlu sonuçlar aldık. Sözleşme aşamasındayız.',
    status: 'completed',
    createdAt: '2026-07-05T09:15:00Z',
    assignedTo: 'Kaan Aksoy',
  },
  {
    id: 'demo-4',
    fullName: 'Alex Carter',
    email: 'alex@cartel-leads.xyz',
    companyName: 'Cartel Leads Ltd.',
    companySize: '1-10',
    requestedPlan: 'growth',
    notes: 'Otomatik reklam dağıtımı hakkında bilgi istiyor. Profil kurumsal olmadığı için elenebilir.',
    status: 'canceled',
    createdAt: '2026-07-04T16:30:00Z',
    assignedTo: 'Mert Yılmaz',
  },
];
