import { SEOMetadata } from '../../types/seo';

export const mockSEOMetadataList: SEOMetadata[] = [
  {
    id: 'seo-1',
    pagePath: '/',
    title: 'Bortesoft - Ultra-Premium SaaS Arayüzleri',
    description: 'Bortesoft ile projenizi Linear ve Apple kalitesinde tasarlayın. En hızlı bento grid oluşturucu ve modern API altyapısı.',
    keywords: ['SaaS', 'Tasarım', 'Bento Grid', 'Linear Estetiği', 'Apple Stil'],
    canonicalUrl: 'https://bortesoft.com',
    ogTitle: 'Bortesoft - Apple & Linear Tarzı Premium SaaS Şablonu',
    ogDescription: 'Sıradanlıktan uzak, her pikseli ince elenmiş, asimetrik bento gridli ve AI destekli otonom SaaS platformu.',
    ogImage: 'https://bortesoft.com/og-main.png',
    twitterImage: 'https://bortesoft.com/twitter-main.png',
    isIndexed: true,
    includeInSitemap: true,
    sitemapPriority: 1.0,
    lastCrawled: '2026-07-06T04:12:00Z',
    score: 98,
    updatedAt: '2026-07-07T10:30:00Z',
  },
  {
    id: 'seo-2',
    pagePath: '/pricing',
    title: 'Esnek Planlar & Adil Fiyatlandırma - Bortesoft',
    description: 'Her ölçekten ekip için esnek, şeffaf ve adil paketler. 14 gün ücretsiz deneyin, dilediğiniz an iptal edin.',
    keywords: ['Bortesoft fiyatlandırma', 'SaaS paketleri', 'Aylık abonelik'],
    canonicalUrl: 'https://bortesoft.com/pricing',
    ogTitle: 'Bortesoft Adil Fiyatlandırma Modülleri',
    ogDescription: 'Kredi kartı gerekmeden anında premium üyelik başlatın. İptal etmek kolaydır, hiçbir gizli ücret yoktur.',
    ogImage: 'https://bortesoft.com/og-pricing.png',
    twitterImage: 'https://bortesoft.com/twitter-pricing.png',
    isIndexed: true,
    includeInSitemap: true,
    sitemapPriority: 0.8,
    lastCrawled: '2026-07-05T03:45:00Z',
    score: 94,
    updatedAt: '2026-07-06T15:20:00Z',
  },
  {
    id: 'seo-3',
    pagePath: '/blog',
    title: 'Tasarım & Geliştirme Günlüğü - Bortesoft Blog',
    description: 'SaaS geliştirme süreçleri, modern UX akımları ve performans iyileştirmeleri hakkında uzmanından makaleler.',
    keywords: ['SaaS blog', 'Yazılım tasarım rehberleri', 'Frontend trendleri'],
    canonicalUrl: 'https://bortesoft.com/blog',
    ogTitle: 'Bortesoft SaaS Tasarım ve Mühendislik Günlüğü',
    ogDescription: 'Linear ve Apple estetiği üzerine yazılmış derin teknik rehberler, hız optimizasyonu ipuçları.',
    ogImage: 'https://bortesoft.com/og-blog.png',
    twitterImage: 'https://bortesoft.com/twitter-blog.png',
    isIndexed: true,
    includeInSitemap: true,
    sitemapPriority: 0.7,
    lastCrawled: '2026-07-04T12:00:00Z',
    score: 88,
    updatedAt: '2026-07-05T11:15:00Z',
  },
  {
    id: 'seo-4',
    pagePath: '/admin/hidden-preview',
    title: '',
    description: '',
    keywords: [],
    canonicalUrl: '',
    ogTitle: '',
    ogDescription: '',
    ogImage: '',
    twitterImage: '',
    isIndexed: false,
    includeInSitemap: false,
    sitemapPriority: 0.1,
    lastCrawled: undefined,
    score: 32,
    updatedAt: '2026-07-02T14:10:00Z',
  }
];
