import { LandingSection } from '../../types/landing-section';

export const mockLandingSections: LandingSection[] = [
  {
    id: 'sec-1',
    key: 'hero',
    name: 'Kahraman (Hero)',
    anchor: '#hero',
    order: 1,
    title: 'Geleceğin SaaS Mimarisi Burada Başlar',
    subtitle: 'Bortesoft ile uygulamanızı Linear ve Apple kalitesinde tasarlayın.',
    description: 'En hızlı bento grid oluşturucu, asimetrik layoutlar ve gömülü AI asistanı ile modern web uygulamaları oluşturun.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-07T12:30:00Z',
    ctaText: 'Ücretsiz Deneyin',
    ctaLink: '/auth/signup'
  },
  {
    id: 'sec-2',
    key: 'problem',
    name: 'Problem',
    anchor: '#problem',
    order: 2,
    title: 'Yavaş ve Karmaşık Geliştirme Süreçlerine Son Verin',
    subtitle: 'Yazılım dünyası sıradan tasarımlardan ve şişirilmiş kodlardan yoruldu.',
    description: 'Geleneksel arayüzler esneklikten uzak, yavaş ve kullanıcı deneyimini kısıtlayan yapılarla dolu. Bortesoft bu sorunu kökten çözer.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-07T11:45:00Z',
    ctaText: 'Çözümü İnceleyin',
    ctaLink: '#modules'
  },
  {
    id: 'sec-3',
    key: 'modules',
    name: 'Modules',
    anchor: '#modules',
    order: 3,
    title: 'Modüler ve Ölçeklenebilir Güçlü Yapı Taşları',
    subtitle: 'Projenizi ayağa kaldıracak hazır, asimetrik modüller.',
    description: 'Kullanıcı yönetimi, faturalandırma entegrasyonu, gelişmiş analitik panelleri ve daha fazlası tak-çalıştır mimariyle hazır.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-06T15:40:00Z',
    ctaText: 'Bileşenleri Keşfet',
    ctaLink: '#features'
  },
  {
    id: 'sec-4',
    key: 'feature-bubbles',
    name: 'Feature Bubbles',
    anchor: '#feature-bubbles',
    order: 4,
    title: 'Mikro-Etkileşimli Akıllı Özellik Balonları',
    subtitle: 'Her noktada kullanıcınıza rehberlik eden canlı arayüz elemanları.',
    description: 'Statik kutular yerine, kullanıcının eylemlerine göre dinamik olarak genişleyen akıllı bildirim ve aksiyon kapsülleri.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-06T12:20:00Z',
    ctaText: 'Balonları Gör',
    ctaLink: '#ai-assistant'
  },
  {
    id: 'sec-5',
    key: 'ai-assistant',
    name: 'AI Assistant',
    anchor: '#ai-assistant',
    order: 5,
    title: 'Kodunuzu ve Arayüzünüzü Yöneten Gömülü Yapay Zeka',
    subtitle: 'Sadece hayal edin, Bortesoft AI Asistanı sizin için kodlasın.',
    description: 'Doğal dilde verdiğiniz talimatları anında premium Tailwind sınıflarına ve optimize edilmiş React bileşenlerine dönüştürür.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-05T14:10:00Z',
    ctaText: 'Asistanı Dene',
    ctaLink: '#ai-coach'
  },
  {
    id: 'sec-6',
    key: 'ai-coach',
    name: 'AI Coach',
    anchor: '#ai-coach',
    order: 6,
    title: 'SaaS Yolculuğunuzda Profesyonel AI Koçu',
    subtitle: 'Metriklerinizi analiz edin, dönüşüm oranlarınızı katlayın.',
    description: 'Kullanıcı analizlerinizi inceleyen akıllı koçunuz, hangi özelliklerin daha çok ilgi çektiğini ve fiyatlandırmayı nasıl optimize etmeniz gerektiğini önerir.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-05T09:12:00Z',
    ctaText: 'Koçla Görüş',
    ctaLink: '#agent-borte'
  },
  {
    id: 'sec-7',
    key: 'agent-borte',
    name: 'Agent Borte',
    anchor: '#agent-borte',
    order: 7,
    title: 'Otonom İş Gücü: Agent Borte Göreve Hazır',
    subtitle: 'Müşteri ilişkileri, teknik destek ve satış süreçlerini otonom yönetin.',
    description: 'Arka planda kesintisiz çalışan Borte, demo taleplerini filtreler, sıkça sorulan soruları yanıtlar ve destek biletlerini çözer.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-04T18:30:00Z',
    ctaText: 'Borte\'yi İncele',
    ctaLink: '#demo'
  },
  {
    id: 'sec-8',
    key: 'demo',
    name: 'Demo Talebi',
    anchor: '#demo',
    order: 8,
    title: 'Bortesoft Deneyimini Kişisel Olarak Keşfedin',
    subtitle: 'Ekibiniz için özel hazırlanmış bir demo randevusu oluşturun.',
    description: 'Sadece 2 dakikada form doldurun, uzman ekibimiz size özel tasarlanmış asimetrik panel önizlemeleriyle birlikte dönüş yapsın.',
    isActive: true,
    publishStatus: 'published',
    updatedAt: '2026-07-04T12:00:00Z',
    ctaText: 'Randevu Al',
    ctaLink: '/demo-request'
  },
  {
    id: 'sec-9',
    key: 'faq',
    name: 'FAQ',
    anchor: '#faq',
    order: 9,
    title: 'Kafanızdaki Soru İşaretlerini Giderelim',
    subtitle: 'Bortesoft altyapısı, güvenliği ve entegrasyon süreçleri hakkında merak edilenler.',
    description: 'Teknik gereksinimlerden fiyatlandırma detaylarına kadar tüm merak edilen soruların detaylı yanıtları.',
    isActive: true,
    publishStatus: 'draft',
    updatedAt: '2026-07-03T16:45:00Z',
    ctaText: 'Tüm Sıkça Sorulanlar',
    ctaLink: '#faq-items'
  }
];
